-- 控制面安全补齐：用户/角色/Token、租户 RLS、告警配置隔离。
-- RLS 使用事务级 app.project_id；服务必须通过 pg.WithProjectTx 访问租户表。

CREATE TABLE IF NOT EXISTS t_role (
    project_id BIGINT NOT NULL REFERENCES t_project(id) ON DELETE CASCADE,
    role_key TEXT NOT NULL,
    name TEXT NOT NULL,
    permissions JSONB NOT NULL DEFAULT '{}'::jsonb,
    enabled BOOLEAN NOT NULL DEFAULT true,
    version BIGINT NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (project_id, role_key)
);

CREATE TABLE IF NOT EXISTS t_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES t_project(id) ON DELETE CASCADE,
    user_key TEXT NOT NULL,
    display_name TEXT NOT NULL DEFAULT '',
    email TEXT NOT NULL DEFAULT '',
    role_key TEXT NOT NULL DEFAULT '',
    status TEXT NOT NULL DEFAULT 'active',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (project_id, user_key),
    FOREIGN KEY (project_id, role_key) REFERENCES t_role(project_id, role_key)
);

CREATE TABLE IF NOT EXISTS t_api_token (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES t_project(id) ON DELETE CASCADE,
    token_name TEXT NOT NULL,
    token_hash BYTEA NOT NULL,
    token_prefix TEXT NOT NULL DEFAULT '',
    scopes JSONB NOT NULL DEFAULT '[]'::jsonb,
    expires_at TIMESTAMPTZ,
    revoked_at TIMESTAMPTZ,
    last_used_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (project_id, token_name),
    UNIQUE (token_hash)
);

CREATE INDEX IF NOT EXISTS idx_user_project_status ON t_user(project_id, status);
CREATE INDEX IF NOT EXISTS idx_api_token_project_active ON t_api_token(project_id, expires_at) WHERE revoked_at IS NULL;

ALTER TABLE t_project ENABLE ROW LEVEL SECURITY;
ALTER TABLE t_device_type ENABLE ROW LEVEL SECURITY;
ALTER TABLE t_device ENABLE ROW LEVEL SECURITY;
ALTER TABLE t_role ENABLE ROW LEVEL SECURITY;
ALTER TABLE t_user ENABLE ROW LEVEL SECURITY;
ALTER TABLE t_api_token ENABLE ROW LEVEL SECURITY;
ALTER TABLE t_external_ref ENABLE ROW LEVEL SECURITY;
ALTER TABLE t_integration_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE t_idem_registry ENABLE ROW LEVEL SECURITY;
ALTER TABLE t_alarm_rule ENABLE ROW LEVEL SECURITY;
ALTER TABLE t_alarm_silence ENABLE ROW LEVEL SECURITY;
ALTER TABLE t_alarm_active ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS tenant_project ON t_project;
CREATE POLICY tenant_project ON t_project
    USING (id = NULLIF(current_setting('app.project_id', true), '')::BIGINT)
    WITH CHECK (id = NULLIF(current_setting('app.project_id', true), '')::BIGINT);

DROP POLICY IF EXISTS tenant_device_type ON t_device_type;
CREATE POLICY tenant_device_type ON t_device_type
    USING (project_id = NULLIF(current_setting('app.project_id', true), '')::BIGINT)
    WITH CHECK (project_id = NULLIF(current_setting('app.project_id', true), '')::BIGINT);

DROP POLICY IF EXISTS tenant_device ON t_device;
CREATE POLICY tenant_device ON t_device
    USING (project_id = NULLIF(current_setting('app.project_id', true), '')::BIGINT)
    WITH CHECK (project_id = NULLIF(current_setting('app.project_id', true), '')::BIGINT);

DROP POLICY IF EXISTS tenant_role ON t_role;
CREATE POLICY tenant_role ON t_role
    USING (project_id = NULLIF(current_setting('app.project_id', true), '')::BIGINT)
    WITH CHECK (project_id = NULLIF(current_setting('app.project_id', true), '')::BIGINT);

DROP POLICY IF EXISTS tenant_user ON t_user;
CREATE POLICY tenant_user ON t_user
    USING (project_id = NULLIF(current_setting('app.project_id', true), '')::BIGINT)
    WITH CHECK (project_id = NULLIF(current_setting('app.project_id', true), '')::BIGINT);

DROP POLICY IF EXISTS tenant_api_token ON t_api_token;
CREATE POLICY tenant_api_token ON t_api_token
    USING (project_id = NULLIF(current_setting('app.project_id', true), '')::BIGINT)
    WITH CHECK (project_id = NULLIF(current_setting('app.project_id', true), '')::BIGINT);

DROP POLICY IF EXISTS tenant_alarm_rule ON t_alarm_rule;
CREATE POLICY tenant_alarm_rule ON t_alarm_rule
    USING (project_id = NULLIF(current_setting('app.project_id', true), ''))
    WITH CHECK (project_id = NULLIF(current_setting('app.project_id', true), ''));

DROP POLICY IF EXISTS tenant_alarm_silence ON t_alarm_silence;
CREATE POLICY tenant_alarm_silence ON t_alarm_silence
    USING (project_id = NULLIF(current_setting('app.project_id', true), ''))
    WITH CHECK (project_id = NULLIF(current_setting('app.project_id', true), ''));

DROP POLICY IF EXISTS tenant_alarm_active ON t_alarm_active;
CREATE POLICY tenant_alarm_active ON t_alarm_active
    USING (project_id = NULLIF(current_setting('app.project_id', true), ''))
    WITH CHECK (project_id = NULLIF(current_setting('app.project_id', true), ''));
