-- 租户可配置的通知端点。敏感 target 由应用层 AES-GCM 加密后保存。
CREATE TABLE IF NOT EXISTS t_notification_endpoint (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES t_project(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    channel TEXT NOT NULL,
    target_ciphertext BYTEA NOT NULL,
    target_nonce BYTEA NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_notification_channel CHECK (channel IN ('webhook','email','sms')),
    UNIQUE (project_id, name)
);
CREATE INDEX IF NOT EXISTS idx_notification_endpoint_project ON t_notification_endpoint(project_id, channel) WHERE enabled;
ALTER TABLE t_notification_endpoint ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_notification_endpoint ON t_notification_endpoint;
CREATE POLICY tenant_notification_endpoint ON t_notification_endpoint
    USING (project_id = NULLIF(current_setting('app.project_id', true), '')::BIGINT)
    WITH CHECK (project_id = NULLIF(current_setting('app.project_id', true), '')::BIGINT);
