-- Human acknowledgement stops unconfirmed escalation and records the actor.
ALTER TABLE t_alarm_active
    ADD COLUMN IF NOT EXISTS confirmed_by TEXT NOT NULL DEFAULT '';
ALTER TABLE t_alarm_active
    ADD COLUMN IF NOT EXISTS acknowledged_at TIMESTAMPTZ;

CREATE TABLE IF NOT EXISTS t_audit_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    action TEXT NOT NULL,
    actor_id TEXT NOT NULL,
    resource_type TEXT NOT NULL,
    resource_id TEXT NOT NULL,
    details JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_audit_log_project_created
    ON t_audit_log(project_id, created_at DESC);
ALTER TABLE t_audit_log ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_audit_log ON t_audit_log;
CREATE POLICY tenant_audit_log ON t_audit_log
    USING (project_id = NULLIF(current_setting('app.project_id', true), '')::BIGINT)
    WITH CHECK (project_id = NULLIF(current_setting('app.project_id', true), '')::BIGINT);
