-- 生产应用账号必须是非 owner、非 superuser；对剩余控制面租户表强制执行 RLS。
ALTER TABLE t_project FORCE ROW LEVEL SECURITY;
ALTER TABLE t_device_type FORCE ROW LEVEL SECURITY;
ALTER TABLE t_device FORCE ROW LEVEL SECURITY;
ALTER TABLE t_role FORCE ROW LEVEL SECURITY;
ALTER TABLE t_user FORCE ROW LEVEL SECURITY;
ALTER TABLE t_api_token FORCE ROW LEVEL SECURITY;
ALTER TABLE t_alarm_rule FORCE ROW LEVEL SECURITY;
ALTER TABLE t_alarm_silence FORCE ROW LEVEL SECURITY;
