-- 网关挂载的子设备台账。子设备不单独持有设备凭据，继承网关认证与租户归属。
CREATE TABLE IF NOT EXISTS t_sub_device (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES t_project(id) ON DELETE CASCADE,
    gateway_device_id BIGINT NOT NULL,
    sub_key TEXT NOT NULL,
    name TEXT NOT NULL DEFAULT '',
    device_type_id BIGINT,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    status TEXT NOT NULL DEFAULT 'active',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uk_sub_device_key UNIQUE (project_id, gateway_device_id, sub_key),
    CONSTRAINT fk_sub_device_gateway FOREIGN KEY (project_id, gateway_device_id)
        REFERENCES t_device(project_id, id) ON DELETE CASCADE,
    CONSTRAINT fk_sub_device_type FOREIGN KEY (project_id, device_type_id)
        REFERENCES t_device_type(project_id, id) ON DELETE RESTRICT,
    CONSTRAINT ck_sub_device_key CHECK (sub_key <> '' AND sub_key !~ '[/#.+]'),
    CONSTRAINT ck_sub_device_status CHECK (status IN ('active','disabled'))
);
CREATE INDEX IF NOT EXISTS idx_sub_device_gateway ON t_sub_device(project_id, gateway_device_id) WHERE status='active';
ALTER TABLE t_sub_device ENABLE ROW LEVEL SECURITY;
ALTER TABLE t_sub_device FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_sub_device ON t_sub_device;
CREATE POLICY tenant_sub_device ON t_sub_device
    USING (project_id = NULLIF(current_setting('app.project_id', true), '')::BIGINT)
    WITH CHECK (project_id = NULLIF(current_setting('app.project_id', true), '')::BIGINT);
GRANT SELECT, INSERT, UPDATE, DELETE ON t_sub_device TO iot_app;
