-- Modbus 轮询控制面配置。点位定义以 JSONB 保存，服务启动时按租户加载。
CREATE TABLE IF NOT EXISTS t_modbus_poll_config (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES t_project(id) ON DELETE CASCADE,
    device_key TEXT NOT NULL,
    device_id BIGINT NOT NULL DEFAULT 0,
    device_type_id BIGINT NOT NULL DEFAULT 0,
    transport TEXT NOT NULL DEFAULT 'tcp',
    endpoint TEXT NOT NULL DEFAULT '',
    serial_path TEXT NOT NULL DEFAULT '',
    baud_rate INT NOT NULL DEFAULT 9600,
    data_bits SMALLINT NOT NULL DEFAULT 8,
    stop_bits SMALLINT NOT NULL DEFAULT 1,
    parity TEXT NOT NULL DEFAULT 'none',
    unit_id SMALLINT NOT NULL DEFAULT 1,
    interval_ms INT NOT NULL DEFAULT 10000,
    timeout_ms INT NOT NULL DEFAULT 5000,
    points JSONB NOT NULL DEFAULT '[]'::jsonb,
    enabled BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uk_modbus_poll_project_device UNIQUE (project_id, device_key),
    CONSTRAINT ck_modbus_poll_transport CHECK (transport IN ('tcp', 'rtu')),
    CONSTRAINT ck_modbus_poll_parity CHECK (parity IN ('none', 'even', 'odd')),
    CONSTRAINT ck_modbus_poll_unit CHECK (unit_id BETWEEN 1 AND 247),
    CONSTRAINT ck_modbus_poll_serial CHECK (baud_rate > 0 AND data_bits BETWEEN 5 AND 8 AND stop_bits IN (1, 2)),
    CONSTRAINT ck_modbus_poll_interval CHECK (interval_ms BETWEEN 100 AND 86400000),
    CONSTRAINT ck_modbus_poll_timeout CHECK (timeout_ms BETWEEN 100 AND 300000),
    CONSTRAINT ck_modbus_poll_points CHECK (jsonb_typeof(points) = 'array')
);
CREATE INDEX IF NOT EXISTS idx_modbus_poll_project_enabled ON t_modbus_poll_config(project_id, enabled);
ALTER TABLE t_modbus_poll_config ENABLE ROW LEVEL SECURITY;
ALTER TABLE t_modbus_poll_config FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_modbus_poll_config ON t_modbus_poll_config;
CREATE POLICY tenant_modbus_poll_config ON t_modbus_poll_config
    USING (project_id = NULLIF(current_setting('app.project_id', true), '')::BIGINT)
    WITH CHECK (project_id = NULLIF(current_setting('app.project_id', true), '')::BIGINT);
GRANT SELECT ON t_modbus_poll_config TO iot_app;
